version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-earnings-app
    restart: always
    env_file:
      - .env
      
      #ports:
      #- "8098:8098"
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true